on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Enter a number'
        required: true
        type: string

jobs:
  fibonacci:
    runs-on: ubuntu-latest
    steps:
      - name: Convert input to integer
        id: convert_input
        run: echo "::set-output name=number::${{ github.event.inputs.number }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Run Fibonacci script
        run: python fibonacci.py ${{ steps.convert_input.outputs.number }}

